"""initial_migration

Revision ID: 628a4eb7624b
Revises: 
Create Date: 2026-05-25 07:37:18.305722+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '628a4eb7624b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_configs',
    sa.Column('config_key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=False),
    sa.Column('api_base_url', sa.String(length=512), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('openid', sa.String(length=128), nullable=True),
    sa.Column('unionid', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('families',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('invite_code', sa.String(length=32), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_invite_code'), 'families', ['invite_code'], unique=True)
    op.create_table('family_members',
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='family_role'), nullable=False),
    sa.Column('nickname_in_family', sa.String(length=64), nullable=True),
    sa.Column('relationship', sa.String(length=64), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_family_members_family_user')
    )
    op.create_table('member_food_preferences',
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('taste_preferences', sa.JSON(), nullable=True),
    sa.Column('favorite_foods', sa.JSON(), nullable=True),
    sa.Column('food_allergies', sa.JSON(), nullable=True),
    sa.Column('dietary_restrictions', sa.JSON(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_member_food_preferences_family_user')
    )
    op.create_table('points_accounts',
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_points_accounts_family_user')
    )
    op.create_table('recipes',
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('display_text', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_family_id'), 'recipes', ['family_id'], unique=False)
    op.create_table('reviews',
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('target_type', sa.Enum('task', 'action', name='review_target_type'), nullable=False),
    sa.Column('target_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('reviewer_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('submitter_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='review_status'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('evidence_photos', sa.JSON(), nullable=True),
    sa.Column('evidence_qrcode', sa.String(length=512), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_family_id'), 'reviews', ['family_id'], unique=False)
    op.create_table('wishes',
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('vision_story', sa.Text(), nullable=True),
    sa.Column('vision_image_url', sa.String(length=512), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('display_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'achieved', 'archived', name='wish_status'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishes_family_id'), 'wishes', ['family_id'], unique=False)
    op.create_table('family_appellations',
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('from_member_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('to_member_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('appellation', sa.String(length=64), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['from_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['to_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'from_member_id', 'to_member_id', name='uq_family_appellations_from_to')
    )
    op.create_table('goals',
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('wish_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('smart_specific', sa.Text(), nullable=True),
    sa.Column('smart_measurable', sa.Text(), nullable=True),
    sa.Column('smart_achievable', sa.Text(), nullable=True),
    sa.Column('smart_relevant', sa.Text(), nullable=True),
    sa.Column('smart_time_bound', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('display_text', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', name='goal_status'), nullable=False),
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wish_id'], ['wishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_family_id'), 'goals', ['family_id'], unique=False)
    op.create_table('points_transactions',
    sa.Column('account_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.Enum('reward', 'penalty', 'manual_adjust', name='points_transaction_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['points_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('goal_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('display_text', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', 'overdue', name='plan_status'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_family_id'), 'plans', ['family_id'], unique=False)
    op.create_table('plan_steps',
    sa.Column('plan_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('step_type', sa.Enum('task', 'action', name='step_type'), nullable=False),
    sa.Column('is_bounty', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='plan_step_status'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plan_step_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('display_text', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('once', 'recurring', name='task_type'), nullable=False),
    sa.Column('recurrence_rule', sa.JSON(), nullable=True),
    sa.Column('time_limit_hours', sa.Float(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('penalty_points', sa.Integer(), nullable=False),
    sa.Column('assignee_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'claimed', 'in_progress', 'submitted', 'approved', 'rejected', 'expired', name='task_status'), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['plan_step_id'], ['plan_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_family_id'), 'tasks', ['family_id'], unique=False)
    op.create_table('actions',
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('plan_step_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('display_text', sa.Text(), nullable=True),
    sa.Column('action_type', sa.Enum('todo', 'schedule', name='action_type'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'submitted', 'approved', 'rejected', name='action_status'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['plan_step_id'], ['plan_steps.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_family_id'), 'actions', ['family_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('family_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('event_type', sa.Enum('schedule', 'todo', 'anniversary', name='calendar_event_type'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('remind_before_days', sa.Integer(), nullable=False),
    sa.Column('action_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_family_id'), 'calendar_events', ['family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_events_family_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_actions_family_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_tasks_family_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('plan_steps')
    op.drop_index(op.f('ix_plans_family_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_table('points_transactions')
    op.drop_index(op.f('ix_goals_family_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_table('family_appellations')
    op.drop_index(op.f('ix_wishes_family_id'), table_name='wishes')
    op.drop_table('wishes')
    op.drop_index(op.f('ix_reviews_family_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_recipes_family_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_table('points_accounts')
    op.drop_table('member_food_preferences')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_families_invite_code'), table_name='families')
    op.drop_table('families')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    op.drop_table('ai_model_configs')
    # ### end Alembic commands ###
